## 7 - 数据透视与合并



<br>

**<font color = '#5172F0'><font size=3.5>必读👇👇👇**</font>
    
现在让我们继续练习 pandas数据分析另一组常用操作 --> **数据透视与合并**


本节习题将涉及四大函数：
    
- pivot_table
- concat
- merge
- join

数据透视表（Pivot Table）是一种常用的数据汇总与分析工具，最典型的应用场景是在 Excel 和 Pandas（Python） 里。它的作用就是：

快速汇总：把原始明细表（往往行数很多）中的数据，按某些字段进行分类、分组和统计。

灵活分析：可以随意拖动“行、列、值、筛选”，生成不同的统计报表。

多维度交叉分析：比如既可以按“地区”统计销售额，也可以再按“年份”细分，形成交叉表

## 数据透视表

![](http://liuzaoqi.oss-cn-beijing.aliyuncs.com/2021/09/14/16316101294678.jpg?域名/sample.jpg?x-oss-process=style/stylename)

### 1 - 加载数据

读取当前目录下 `"某超市销售数据.csv"` 并设置千分位符号为 `,`

In [1]:
import pandas as pd
df = pd.read_csv("某超市销售数据.csv", thousands=',')
df.pivot_table(values='销售额', index='省/自治区')

               销售额
省/自治区
上海     1875.712934
云南     1863.789030
内蒙古    1314.826316
北京     1726.857143
吉林     1701.563567
四川     1157.875536
天津     1611.206667
宁夏     1651.680000
安徽     1477.868251
山东     1642.659111
山西     1751.359184
广东     1592.185340
广西     1675.061135
新疆     1402.384615
江苏     1279.898089
江西     1966.477876
河北     1780.275248
河南     1558.400335
浙江     1347.277778
海南     1721.982759
湖北     1324.808442
湖南     1603.702222
甘肃     1602.893443
福建     1732.044693
西藏      201.000000
贵州     1425.978723
辽宁     1363.381982
重庆     1383.082927
陕西     1880.606635
青海     2978.954545
黑龙江    1800.438503

### 2 - 数据透视｜默认

制作各省「平均销售额」的数据透视表

In [3]:
pivot_2 = df.pivot_table(values='销售额', index='省/自治区')
print(pivot_2.round(2))
print("\n" + "-"*50 + "\n")

           销售额
省/自治区
上海     1875.71
云南     1863.79
内蒙古    1314.83
北京     1726.86
吉林     1701.56
四川     1157.88
天津     1611.21
宁夏     1651.68
安徽     1477.87
山东     1642.66
山西     1751.36
广东     1592.19
广西     1675.06
新疆     1402.38
江苏     1279.90
江西     1966.48
河北     1780.28
河南     1558.40
浙江     1347.28
海南     1721.98
湖北     1324.81
湖南     1603.70
甘肃     1602.89
福建     1732.04
西藏      201.00
贵州     1425.98
辽宁     1363.38
重庆     1383.08
陕西     1880.61
青海     2978.95
黑龙江    1800.44

--------------------------------------------------

### 3 - 数据透视｜指定方法

制作各省「销售总额」的数据透视表

In [4]:
df.pivot_table(values='销售额', index='省/自治区', aggfunc='sum')

           销售额
省/自治区
上海      594601
云南      441718
内蒙古     249817
北京      350552
吉林      896724
四川      269785
天津      483362
宁夏       41292
安徽      684253
山东     1884130
山西      429083
广东     1520537
广西      383589
新疆       72924
江苏      401888
江西      222212
河北      899039
河南      930365
浙江      266761
海南       99875
湖北      408041
湖南      721666
甘肃      195553
福建      620072
西藏         201
贵州       67021
辽宁      756677
重庆      283532
陕西      396808
青海       65537
黑龙江    1346728

### 4 - 数据透视｜多方法

制作各省「销售总额」与「平均销售额」的数据透视表

### 5 - 数据透视｜多指标

制作各省市「销售总额」与「利润总额」的数据透视表

### 6 - 数据透视｜多索引

制作「各省市」与「不同类别」产品「销售总额」的数据透视表

### 7 - 数据透视｜多层

制作各省市「不同类别」产品的「销售总额」透视表

### 8 - 数据透视｜综合

制作「各省市」、「不同类别」产品「销售量与销售额」的「均值与总和」的数据透视表，并在最后追加一行『合计』

### 9 - 数据透视｜筛选

在上一题的基础上，查询 **「类别」** 等于 **「办公用品」** 的详情

### 10 -数据透视｜逆透视

逆透视就是将宽的表转换为长的表，例如将第 5 题的透视表进行逆透视，其中不需要转换的列为『数量』列